fix: rmdir没有找到目录时不打印日志
DragonOS-Community/NovaShell pull request #29
Opened 2024-03-12 16:05 UTC by 1037827920

2024-03-12 16:41 UTC, fslongjin requested changes

2024-03-12 16:41 UTC, fslongjin commented on src/shell/command/mod.rs
> +        let path = args.get(0).unwrap();
不能直接unwrap，否则将会造成shell的panic。应当返回错误。

2024-03-12 16:41 UTC, fslongjin commented on src/shell/command/mod.rs
> +            Ok(readdir) => readdir,
使用ok_or方法，而不是这种match

2024-03-12 16:41 UTC, fslongjin commented on src/shell/command/mod.rs
> +            if entry.file_type().unwrap().is_dir()
同样的问题，不能直接unwrap。要对空的情况做处理。

2024-03-13 00:20 UTC, 1037827920 commented on src/shell/command/mod.rs
> +            Ok(readdir) => readdir,
不使用match的话，ok_or要取出Ok里面的值只能使用unwrap，但是unwrap返回的Result类型跟函数返回的不一样，还是用match比较好吧

2024-03-13 04:25 UTC, fslongjin commented
你可以让gpt帮你改写一下，因为这种写法以后（估计就这一两个月会加上）肯定会在clippy的检查之中报错的，这个不符合rust的那种最佳实践



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月13日(周三) 上午8:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DragonOS-Community/NovaShell] fix: rmdir没有找到目录时不打印日志 (PR #29)




 
@1037827920 commented on this pull request.
 
 
In src/shell/command/mod.rs:
 &gt; @@ -417,7 +417,36 @@ impl Shell {          if unlikely(args.len() != 1) {              return Err(CommandError::WrongArgumentCount(args.len()));          } -        let path = self.is_dir(args.get(0).unwrap())?; + +        let path = args.get(0).unwrap(); +        let mut parent = Self::current_dir(); +        let mut child = path.clone(); +        if let Some(index) = path.rfind('/') { +            let (str1, str2) = path.split_at(index + 1); +            parent = String::from(str1); +            child = String::from(str2); +        } + +        let dir = match fs::read_dir(Path::new(&amp;parent)) { +            Ok(readdir) =&gt; readdir,  
不使用match的话，ok_or要取出Ok里面的值只能使用unwrap，但是unwrap返回的Result类型跟函数返回的不一样，还是用match比较好吧
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;

2024-03-13 04:41 UTC, fslongjin commented on src/shell/command/mod.rs
> +            Ok(readdir) => readdir,
> unwrap返回的Result类型跟函数返回的不一样

Result类型err部分不一样的话就用map_err。 而且ok_or之后再加`?`就能自动把错误值给抛出去

2024-03-13 04:49 UTC, 1037827920 commented on src/shell/command/mod.rs
> +            Ok(readdir) => readdir,
ok

2024-03-15 13:53 UTC, closed without merging